algo = input('Digite alguma coisa: ')
print('O tipo primitivo eh: ', type(algo))
print('So tem espaços? ', algo.isspace())
print('E alfabetico? ', algo.isalpha())
print('E alfanumerico? ', algo.isalnum())
print('esta em maiusculas? ', algo.isupper())
print('esta em minusculas? ', algo.islower())
print('esta Capitalizadas? ', algo.istitle())